#!/bin/csh

#setenv LSB_JOB_REPORT_MAIL N

setenv LOCALDIR `pwd`
setenv EXECDIR /afs/cern.ch/work/j/jing/private/FCPPL/learning_NN/simpleBP_MEM/NN_MEM_moreInput/NN_MEM_git/NN_MEM_Minimizer/test

setenv LC_ALL "en_US.UTF-8"

setenv LHAPDF /afs/cern.ch/work/j/jing/public/IPHCNtuple/LHAPDF-6.1.5/../LHAPDF-6.1.5-install
setenv LHAPATH $LHAPDF/share/LHAPDF/
setenv LHAPDF_BIN $LHAPDF/bin
setenv PATH ${PATH}:${LHAPDF_BIN}
setenv LD_LIBRARY_PATH ${LD_LIBRARY_PATH}:$LHAPDF/lib

#setenv ROOTSYS /usr/bin/root
rehash

cd ${EXECDIR}
eval `scram runtime -csh`

cd ${LOCALDIR}
${EXECDIR}/./test > log_output

ls

cp output_ttH.root /afs/cern.ch/work/j/jing/private/FCPPL/learning_NN/simpleBP_MEM/NN_MEM_moreInput/NN_MEM_git/NN_MEM_Minimizer/test/test_Batch/
cp output_ttW.root /afs/cern.ch/work/j/jing/private/FCPPL/learning_NN/simpleBP_MEM/NN_MEM_moreInput/NN_MEM_git/NN_MEM_Minimizer/test/test_Batch/
cp output_ttZ.root /afs/cern.ch/work/j/jing/private/FCPPL/learning_NN/simpleBP_MEM/NN_MEM_moreInput/NN_MEM_git/NN_MEM_Minimizer/test/test_Batch/
cp log_output /afs/cern.ch/work/j/jing/private/FCPPL/learning_NN/simpleBP_MEM/NN_MEM_moreInput/NN_MEM_git/NN_MEM_Minimizer/test/test_Batch/
